### ISSUE TITLE
Pointer Egzersiz Önerisi

### ISSUE THREAD

**Issue by coderkan** [esencgr/Cpp_deitel_exercise_pointers#1]
Merhaba Çağrı,

Pointerları kullanmanda sana fikir katması amacı ile https://www.tutorialspoint.com/c_standard_library/string_h.htm **string.h** kütüphanesinin örneklerini kendin yapabilirsin. Mesela kendi **strlen**'ini yazabilirsin. Çoğunluğu pointer ile yapılan işlemlerdir. 
Fikir katar sana.

İyi çalışmalar.
Erkan

**Comment by esencgr** [comment]
Selamlar hocam,

Teşekkür ederim tavsiyeniz ve değerli fikirleriniz için. 

İyi günler dilerim.

**Comment by esencgr** [comment]
Merhabalar hocam,
Tavsiyeniz üzerine birşeyler yapmaya çalıştım..
[strlen.cpp.txt](https://github.com/esencgr/Cpp_deitel_exercise_pointers/files/3249719/strlen.cpp.txt)

**Comment by esencgr** [comment]
Merhaba hocam,
Tavsiyeniz üzerine çalıştım.
[strlen_func.txt](https://github.com/esencgr/Cpp_deitel_exercise_pointers/files/3249723/strlen_func.txt)

**Comment by esencgr** [comment]
Merhaba hocam,
Tavsiyeniz üzerine çalıştım..
[strlen_func.txt](https://github.com/esencgr/Cpp_deitel_exercise_pointers/files/3249728/strlen_func.txt)

**Comment by esencgr** [comment]
Merhaba hocam, 
Tavsiyeniz üzerine biraz çalıştım.
```
// writing a function that who does strlen task.
#include <iostream>
#include <string>
using namespace std;

int my_strlen ( const char * );

int main(){

    char str[ 30 ];
    cin.getline ( str, 30 );
    int size = my_strlen ( str );
    cout << "The string is include " <<  size << "character " << endl;

    return 0;
}

// In ths function, s_ptr is a pointer that defined a character constant.
// The characters can't changes using by s_ptr. 
int my_strlen ( const char *s_ptr ){           // the function hasn't got first variable assignment.
     int count = 0;
     for ( ;  *s_ptr != '\0';  *s_ptr++ )
         count++;

      return count;
}

```

**Comment by coderkan** [comment]
Merhaba Çağrı,

Gayet güzel olmuş. 
Ellerine sağlık.
